name: Build após merge do PR

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
      - name: Verificar código
        uses: actions/checkout@v3

      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Compilar código Java
        run: |
          mkdir -p out
          find app/src -name "*.java" > sources.txt
          javac -d out @sources.txt

      - name: Rodar aplicação
        run: java -cp out br.com.ivblour.Main
